@baseAdress = http://localhost:5116

GET {{baseAdress}}/api/categories
Accept: application/json

###
Post {{baseAdress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Category",
  "description": "Description of the new category"
}

###
